README.md
This PR adds the codeship badge to the README file.
=> Add Codeship Badge

README.md, app/helpers/shipyard/alert_helper.rb, app/helpers/shipyard/form_helper.rb, spec/helpers/alert_helper_spec.rb, spec/helpers/box_helper_spec.rb, spec/helpers/form_helper_spec.rb, spec/helpers/note_helper_spec.rb
This PR fills out the testing for most of the other helpers.
=> Test All Helpers

ci/percy, ci/rspec, ci/setup, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock
Trying to ignore the gh-pages branch.
=> Ignore the gh-pages branch.

styleguide/_includes/page-heading.html, styleguide/_layouts/application.html, styleguide/components/alerts.md, styleguide/components/boxes.md, styleguide/components/buttons.html, styleguide/components/code.html, styleguide/components/empty-states.html, styleguide/components/forms.html, styleguide/components/grid.md, styleguide/components/icons.html, styleguide/components/index.html, styleguide/components/modals.html, styleguide/components/notes.md, styleguide/components/tooltips.md, styleguide/utilities/colors.html, styleguide/utilities/index.html, styleguide/utilities/responsive.md, styleguide/utilities/typography.html
This PR makes some small improvements to the documentation — mostly for the purpose of making it easier to maintain.
=> Documentation Improvements

assets/stylesheets/shipyard/_components.sass, assets/stylesheets/shipyard/components/_boxes.sass, assets/stylesheets/shipyard/components/_header.sass, assets/stylesheets/shipyard/mixins/_box-model.sass, assets/stylesheets/shipyard/variables/_misc.sass, styleguide/_layouts/application.html, styleguide/_sass/layout.sass
This PR adds a header component to Shipyard and uses it straight away for the styleguide.
=> Add Header Component

lib/shipyard-framework.rb, lib/shipyard-framework/jekyll/shipyard_css_classes.rb, styleguide/_layouts/application.html, styleguide/utilities/colors.md
This PR adds a unique class to each generated page in a Jekyll application.
=> Jekyll Unique Page Classes

ci/jekyll, ci/percy, ci/setup, shipyard.gemspec
This PR tests Jekyll as a separate pipeline in the CI workflow.
=> Test Jekyll

assets/stylesheets/shipyard/components/_hamburger.sass, assets/stylesheets/shipyard/components/_header.sass, assets/stylesheets/shipyard/variables/_components.scss, styleguide/_layouts/application.html, styleguide/_sass/layout.sass, styleguide/_sass/views.sass, styleguide/assets/js/application.es6, styleguide/components/index.html, styleguide/utilities/index.html
This PR makes the header component responsive.
=> Responsive Header

ci/jekyll, ci/percy, lib/shipyard-framework.rb, lib/shipyard-framework/jekyll/shipyard_css_classes.rb, lib/shipyard-framework/jekyll/shipyard_variables.rb
This PR adds environment variables to the html tags.
=> Jekyll Environment Vars

ci/deploy, ci/jekyll, ci/percy, ci/rspec, ci/setup, styleguide/_config.yml, styleguide/index.html, styleguide/index.md
This PR attemps to automate the deploys to GitHub Pages after a PR merges.
=> Auto-deploy to GitHub Pages

README.md, assets/stylesheets/shipyard/components/_code.sass, styleguide/_assets/css/views.sass, styleguide/index.md
This PR adds more documentation around installation.
=> Add Documentation Installation

assets/stylesheets/shipyard/_components.sass, assets/stylesheets/shipyard/components/_tables.sass, styleguide/_layouts/application.html, styleguide/components/index.html, styleguide/components/tables.html, styleguide/components/tables.md
This PR adds a simple table component with alternating rows.
=> Table Component

assets/javascripts/shipyard.es6, assets/javascripts/shipyard/core.es6, assets/javascripts/shipyard/scroll.es6, ci/deploy, ci/jekyll, ci/percy
This PR handles the scroll states in standard JavaScript to remove the need for jQuery in other places.
=> Scroll States

.travis.yml
This PR tests out the Travis "Stages" concept which is similar to Codeship Parallel Pipelines
=> Travis Stages

.travis.yml, ci/deploy, ci/jekyll
This PR fixes up some of the CI issues that were recently introduced, and should hopefully produce better logs.
=> Deploy Dry-Runs

assets/stylesheets/shipyard/_components.sass, assets/stylesheets/shipyard/_utilities.sass, assets/stylesheets/shipyard/components/_boxes.sass, assets/stylesheets/shipyard/core/_grid.sass, assets/stylesheets/shipyard/utilities/_margin.sass, assets/stylesheets/shipyard/utilities/_typography.sass, ci/deploy, ci/percy, styleguide/_assets/css/application.sass, styleguide/_assets/css/views.sass, styleguide/components/grid.md
This PR turns the current grid system which is primarily based on floats into a flexbox-based grid.
=> Flexbox Grid

.travis.yml
This stops the rubygem from trying to deploy twice on master.
=> Improve the RubyGem Deploys

styleguide/utilities/grid.md
This PR fixes a small error that I made regarding the code documentation for fixing responsive grids.
=> Fix Responsive Grid Docs

assets/stylesheets/shipyard/components/_forms.sass, assets/stylesheets/shipyard/utilities/_display.sass, lib/shipyard-framework/version.rb, styleguide/index.md
This PR adds utility classes for `.display-flex` and upgrades Shipyard to version `0.5.52`.
=> Add Display Flex

styleguide/_assets/css/views.sass, styleguide/utilities/grid.md
=> Document Nested Columns

styleguide/_assets/css/fonts.sass, styleguide/_assets/css/vendor.sass, styleguide/_layouts/application.html
This PR fixes some of the issues in the styleguide that came out as recommendations in the Chrome audit tool.
=> Chrome Audit Fixes

assets/stylesheets/shipyard/_mixins.sass, assets/stylesheets/shipyard/components/_forms.sass, assets/stylesheets/shipyard/mixins/_icon.sass, assets/stylesheets/shipyard/mixins/_icons.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock
This PR makes the select box drop arrow icons red when in the error state.
=> Improve Select Box Icons

assets/stylesheets/shipyard/utilities/_grid.sass, assets/stylesheets/shipyard/variables/_color_utilities.sass, assets/stylesheets/shipyard/variables/_colors.scss, lib/shipyard-framework/helpers/icon_helper.rb, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/_assets/css/views.sass, styleguide/_plugins/color_css_class.rb, styleguide/utilities/colors.md, styleguide/utilities/grid.md
This PR makes the following minor improvements to the Shipyard utilities:
- Adds `black` and `white` to the color utilities.
- Adds a `0%` or `auto` column to the grid utilities for allowing people to turn something into an automatically sized column as the screen gets larger.
=> Minor Upgrade to Color & Grid Utilities

styleguide/_assets/css/syntax.css, styleguide/_layouts/application.html, styleguide/components/icons.md
Added syntax highlighting via the following command:
```
rougify style github > _assets/css/syntax.css
```
---
=> Add Syntax Highlighting to Documentation

assets/stylesheets/shipyard/utilities/_border-radius.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/_data/breakpoints.yml, styleguide/_plugins/component_css_class.rb, styleguide/utilities/border-radius.md
This PR renames the `.rds` classes to `.rounded` to be a little friendlier, and also introduces responsiveness to the utilities as well.
=> Responsive Border-Radius Utilities

assets/stylesheets/shipyard/components/_input-switch.sass, assets/stylesheets/shipyard/components/_modals.sass, assets/stylesheets/shipyard/utilities/_grid.sass, assets/stylesheets/shipyard/utilities/_margin-padding.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/_assets/css/views.sass, styleguide/components/checkboxes.md, styleguide/utilities/colors.md, styleguide/utilities/grid.md, styleguide/utilities/margin-padding.md
This PR improves some of the utility classes of Shipyard and bumps to `0.5.74`
=> Version 0.5.74

assets/stylesheets/shipyard/components/_forms.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/components/forms.html, styleguide/components/forms.md
This PR adds a style for read-only inputs (via the `.input-readonly` class).
=> Read-Only Inputs

assets/stylesheets/shipyard/_utilities.sass, assets/stylesheets/shipyard/utilities/_accordion.sass, ci/sass_lint, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock
Added support for an `accordion` utility that opens and closes a section of content more gracefully.
=> Accordion Utility

assets/stylesheets/shipyard/utilities/_accordion.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock
Adds support for the CSS transition of the margin property when an accordion is closed.
=> Accordion Margin Transitions

assets/javascripts/shipyard.es6, assets/javascripts/shipyard/accordion.es6, assets/javascripts/shipyard/core.es6, assets/javascripts/shipyard/modal-trigger.es6, assets/stylesheets/shipyard/utilities/_accordion.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/utilities/accordion.md, styleguide/utilities/index.md
This PR adds documentation around the `.accordion` utility, and makes a few minor improvements in the previous styles.
=> Accordion Documentation

assets/icons/arrows/arrow-down.svg, assets/icons/arrows/arrow-left.svg, assets/icons/arrows/arrow-right.svg, assets/icons/arrows/arrow-up.svg, assets/stylesheets/shipyard/components/_icons.sass, assets/stylesheets/shipyard/mixins/_components.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/components/icons.md
Added arrow icons for all directions
=> Arrow Icons

assets/stylesheets/shipyard/components/_input-switch.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/components/checkboxes.md
=> Warning Switches

Jenkinsfile, Rakefile, assets/stylesheets/shipyard/core/_reset.sass, ci/deploy, ci/jekyll, ci/percy, styleguide/_config.yml
Introduce Jenkins Input Steps
- https://plugins.jenkins.io/pipeline-input-step
- https://jenkins.io/doc/pipeline/steps/pipeline-input-step/
=> Jenkins Input Steps

Rakefile, ci/build.rb, ci/deploy, styleguide/_config.yml
This PR should fix the deploy steps on Codeship builds.
=> Fix Deploy Steps

Jenkinsfile
Removed the input steps from Jenkins deploys.
=> Don't Pause Deploys

Jenkinsfile
so things don't hang around for ever
=> timeout waiting for input

Jenkinsfile, assets/stylesheets/shipyard/_functions.sass, assets/stylesheets/shipyard/components/_tooltips.sass, assets/stylesheets/shipyard/functions/_opposite-direction.sass, assets/stylesheets/shipyard/utilities/_typography.sass, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/_plugins/sass_output.rb, styleguide/components/horizontal-rules.md, styleguide/components/modals/index.md, styleguide/components/tooltips.md
=> Flexible Tooltips

Jenkinsfile, assets/stylesheets/shipyard/_utilities.sass, assets/stylesheets/shipyard/_variables.sass, assets/stylesheets/shipyard/components/_tooltips.sass, assets/stylesheets/shipyard/utilities/_overflow.sass, assets/stylesheets/shipyard/utilities/_typography.sass, assets/stylesheets/shipyard/variables/_components.scss, assets/stylesheets/shipyard/variables/_misc.sass, assets/stylesheets/shipyard/variables/_z-index.scss, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/components/tooltips.md, styleguide/utilities/index.md, styleguide/utilities/overflow.md
This PR fixes a few issues with the default tooltips makes it easier to adjust the default styles later.
=> Tooltip Fixes

assets/stylesheets/shipyard/_utilities.sass, assets/stylesheets/shipyard/utilities/_visibility.sass, assets/stylesheets/shipyard/variables/_options.scss, lib/shipyard-framework/version.rb, styleguide/Gemfile.lock, styleguide/_data/utilities.yml, styleguide/utilities/visibility.md
This PR adds the visibility utility and upgrades to `0.9.0`
=> Visibility Property

assets/stylesheets/shipyard/variables/_colors.scss, styleguide/Gemfile.lock
Fixes the `Gemfile.lock` that should have been changed in #126
=> Fix Gemfile.lock

styleguide/Gemfile.lock, styleguide/_assets/js/vendor/prod-perfect.js
=> Prod-Perfect Tracking
